# Generated by Django 3.2 on 2021-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210502_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalorder', models.ManyToManyField(to='cart.Order')),
            ],
        ),
    ]
