# Generated by Django 3.2 on 2021-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
