# Generated by Django 3.2.4 on 2021-06-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210608_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingaddress',
        ),
        migrations.AddField(
            model_name='order',
            name='billingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.billingaddress'),
        ),
    ]
