# Generated by Django 3.2.4 on 2021-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20210608_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bankingname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentoption',
        ),
        migrations.AddField(
            model_name='items',
            name='discountedprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(choices=[('kg', 'Kg'), ('500gm', '500gm'), ('250gm', '250gm')], default='Not delivered', max_length=100),
        ),
    ]
