# Generated by Django 3.2.4 on 2022-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_order_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='weight',
        ),
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='Medium', max_length=100),
        ),
    ]
