# Generated by Django 3.2.4 on 2022-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20220203_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='size',
        ),
        migrations.AddField(
            model_name='items',
            name='frame_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='items',
            name='style',
            field=models.CharField(choices=[('R', 'RECTANGLE'), ('RO', 'ROUND')], default='RECTANGLE', max_length=100),
        ),
    ]
