# Generated by Django 3.2.4 on 2022-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20220225_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
