# Generated by Django 3.2.4 on 2022-03-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_items_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='price',
            new_name='dis_price',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='discountedprice',
            new_name='originalprice',
        ),
    ]
